<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predicting risk factors for maternal mortality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="health_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="health_analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="health_analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="health_analysis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="health_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="health_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="health_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="health_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="health_analysis_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="health_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="health_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="health_analysis_files/libs/bootstrap/bootstrap-090d550c8cf1ac4109d95fb271557244.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#split-data" id="toc-split-data" class="nav-link" data-scroll-target="#split-data">Split Data</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda">EDA</a></li>
  <li><a href="#data-validation" id="toc-data-validation" class="nav-link" data-scroll-target="#data-validation">Data Validation</a></li>
  <li><a href="#model-construction" id="toc-model-construction" class="nav-link" data-scroll-target="#model-construction">Model construction</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../health_analysis.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting risk factors for maternal mortality</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Apoorva Srivastava, Gloria (Guaner) Yi, Jeffrey Ding &amp; Randall Lee </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>Despite advancements in medicine and technology, maternal mortality remains a prevalent issue impacting many women in developing countries. The general consensus is that maternal mortality is a multidimensional issue that is complicated by many socioeconomic determinants of health and barriers to access. This project aims to investigate the viability of using a Support Vector Classifier (SVC) trained on open-source maternal health measurements to predict the risk intensity levels (low, medium, or high) of pregnant women. Our final classifier performed fairly well on an unseen test data set, with a weighted recall score of 0.77 and an overall accuracy of 0.77. Out of the 305 test data cases, it correctly predicted 235 cases. The model showed particularly strong performance in identifying high-risk pregnancies, achieving an AUV of 0.943 for the high-risk class, compared to 0.820 for low-risk class and 0.814 for medium-risk class. However, the model made notable errors where 13 high-risk cases were misclassified as 11 medium-risk and 2 low-risk. These false negatives are gaps where high-risk individuals may not receive the necessary care. We recommend further research to improve the model’s sensitivity to high-risk cases and better differentiate between medium and low-risk categories before it is ready to be put into production in clinical settings. Additional feature engineering or exploring ensemble methods may help reduce these critical misclassifications. The implementation of refined classifiers would expand the capabilities of most healthcare systems and increase the efficacy of monitoring and interventions in underprivileged communities.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Maternal mortality is a serious issue that predates human history and still affects many mothers today. Among women of reproductive age, 9% of global deaths are currently attributable to maternal causes such as hemorrhaging, hypertension, and unsafe abortion <span class="citation" data-cites="hassfurter2025trends">(<a href="#ref-hassfurter2025trends" role="doc-biblioref">Hassfurter 2025</a>)</span>. Fortunately, gradual improvements in medical understanding, policy, healthcare, and overall quality of life have led to steadily decreasing maternal mortality rates. Recent UNICEF reports from 2023 place the global maternal mortality ratio at 197 per 100,000 live births, which is approximately 40% less than the reported ratio from 2000. Although many countries report mortality rates on par with the global average, there are an overwhelming number of rural and underserved communities within these countries that continue to experience disproportionate rates of maternal mortality.</p>
<p>One such country is Bangladesh, which has an overall maternal mortality ratio of 196 per 100,000 live births that appears to match the global rates; however, deeper investigation reveals significant differences in mortality rate between women of different socioeconomic backgrounds. A study conducted by Aniqa Tasnim Hossain and their team from Bangladesh’s International Centre for Diarrhoeal Disease Research noted the following findings:</p>
<blockquote class="blockquote">
<p>“women living in rural areas and those of poorer socioeconomic status were more likely to die due to maternal causes of deaths. Most deaths occurred on the day of and one day after delivery. We identified haemorrhage and eclampsia as the major contributors to maternal deaths. We also found a large proportion of deaths occurring in-transit with substantial shuttling for care seeking before their deaths. <span class="citation" data-cites="hossain2023maternal">(<a href="#ref-hossain2023maternal" role="doc-biblioref">Hossain et al. 2023</a>)</span>”</p>
</blockquote>
<p>In their conclusions, <span class="citation" data-cites="hossain2023maternal">Hossain et al. (<a href="#ref-hossain2023maternal" role="doc-biblioref">2023</a>)</span> recommended investing in a structured referral system and emergency transportation to prioritize delivering timely interventions for haemorrhaging or eclampsia. This sentiment is echoed in a paper published in <em>The Lancet</em> that performed a global analysis of the determinants in marternal health and mortality <span class="citation" data-cites="souza2023global">(<a href="#ref-souza2023global" role="doc-biblioref">Souza et al. 2023</a>)</span>. <span class="citation" data-cites="souza2023global">Souza et al. (<a href="#ref-souza2023global" role="doc-biblioref">2023</a>)</span> argues that focusing research on the biomedical causes of mortality is insufficient, and more attention should be directed towards goals such as “primary prevention, early identification, and adequate management of pregnancy, labour, and postpartum complications”.</p>
<p>Both reports highlight a growing need for the ability to identify and prioritize high-risk mothers in order to accurately and punctually deliver care. A welcome innovation has been the development of wearable technology and internet-enabled devices. These devices have allowed patients and physicians to reliably monitor health conditions from their homes and enabled the collection of physiological data from otherwise underserved communities. In 2020, <span class="citation" data-cites="ahmed2020data">Ahmed et al. (<a href="#ref-ahmed2020data" role="doc-biblioref">2020</a>)</span> used these devices as well as available medical records to build maternal health dataset of rural Bangladesh, which was later uploaded to the UC Irvine Machine Learning Repository. This project seeks to predict maternal health risk levels using an SVC model and the Maternal Health Risk dataset. The ability to accurately predict high-risk pregnancies would allow timely and focused medical interventions for vulnerable individuals.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>The data set used in this project is of health conditions of pregnant women from the rural areas of Bangladesh created by Marzia Ahmed at Daffodil International University. This dataset was sourced from the UC Irvine Machine Learning Repository and can be found <a href="https://archive.ics.uci.edu/dataset/863/maternal+health+risk">here</a>. Each observation in the dataset corresponds to a pregnant individual’s health profile, comprising a risk intensity level (low, medium, or high risk) and associated clinical measurements including demographic information (age) and vital signs (systolic blood pressure, diastolic blood pressure, blood glucose concentration, body temperature, and resting heart rate). The data set was collected via an IoT-based risk monitoring system from hospitals, community clinics, and maternal health cares in rural Bangladesh.</p>
<section id="data-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="data-dictionary">Data dictionary</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Column Name</th>
<th>Role</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age</td>
<td>Feature</td>
<td>Integer</td>
<td>Age of the patient during pregnancy (in years)</td>
</tr>
<tr class="even">
<td>SystolicBP</td>
<td>Feature</td>
<td>Integer</td>
<td>Systolic (upper) blood pressure measured in mmHg</td>
</tr>
<tr class="odd">
<td>DiastolicBP</td>
<td>Feature</td>
<td>Integer</td>
<td>Diastolic (lower) blood pressure measured in mmHg</td>
</tr>
<tr class="even">
<td>BS</td>
<td>Feature</td>
<td>Integer</td>
<td>Blood sugar level measured in mmol/L</td>
</tr>
<tr class="odd">
<td>BodyTemp</td>
<td>Feature</td>
<td>Integer</td>
<td>Body temperature of the patient measured in °F</td>
</tr>
<tr class="even">
<td>HeartRate</td>
<td>Feature</td>
<td>Integer</td>
<td>Patient’s resting heart rate measured in bpm</td>
</tr>
<tr class="odd">
<td>RiskLevel</td>
<td>Target</td>
<td>Categorical</td>
<td>Predicted pregnancy risk level based on clinical features</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<p>SVC was used to build a classification model to predict risk levels for pregnant women in rural Bangladesh. With the exception of diastolic blood pressure, all variables from the original dataset were included for analysis. The features used were age, systolic blood pressure, blood glucose level (BS), body temperature, and heart rate. Data was partitioned into a 70:30 train-test split and the random_state was set to 123 for reproducibility. We performed hyperparameter tuning using randomized search with 10-fold cross-validation and recall score (weighted) as our evaluation metric to select the optimal values for C (regularization parameter), gamma (kernel coefficient). Recall score was selected to optimize the model for sensitivity in predicting high-risk cases. All explanatory variables were numerical and were standardized via StandardScalar prior to fitting. The Python programming language and the following Python packages were used to perform the analysis: requests <span class="citation" data-cites="reitz2023requests">(<a href="#ref-reitz2023requests" role="doc-biblioref">Reitz et al. 2023</a>)</span>, numpy <span class="citation" data-cites="harris2020array">(<a href="#ref-harris2020array" role="doc-biblioref">Harris et al. 2020</a>)</span>, Pandas <span class="citation" data-cites="mckinney2010data">(<a href="#ref-mckinney2010data" role="doc-biblioref">McKinney et al. 2010</a>)</span>, pandera <span class="citation" data-cites="niels_bantilan_2023_pandera">(<a href="#ref-niels_bantilan_2023_pandera" role="doc-biblioref">Bantilan 2023</a>)</span>, altair <span class="citation" data-cites="vanderplas2018altair">(<a href="#ref-vanderplas2018altair" role="doc-biblioref">VanderPlas et al. 2018</a>)</span>, matplotlib <span class="citation" data-cites="hunter2007matplotlib">(<a href="#ref-hunter2007matplotlib" role="doc-biblioref">Hunter 2007</a>)</span>, seaborn <span class="citation" data-cites="waskom2021seaborn">(<a href="#ref-waskom2021seaborn" role="doc-biblioref">Waskom 2021</a>)</span>, deepchecks <span class="citation" data-cites="deepchecks">(<a href="#ref-deepchecks" role="doc-biblioref">Deepchecks 2022</a>)</span>, scikit-learn <span class="citation" data-cites="pedregosa2011scikit">(<a href="#ref-pedregosa2011scikit" role="doc-biblioref">Pedregosa et al. 2011</a>)</span>, and scipy <span class="citation" data-cites="virtanen2020scipy">(<a href="#ref-virtanen2020scipy" role="doc-biblioref">Virtanen et al. 2020</a>)</span>.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="split-data" class="level2">
<h2 class="anchored" data-anchor-id="split-data">Split Data</h2>
<p>Ahmed’s Maternal Health Risk dataset was read into a data frame and split 70:30 into a training dataset and testing dataset, respectively. The training dataset was used to build and train the model, and the test data was maintained separately for objective evaluation of the model’s performance. A random seed was saved to ensure reproducibility of the data split.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-raw-data" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-raw-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Raw Maternal Health Risk Data
</figcaption>
<div aria-describedby="tbl-raw-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">SystolicBP</th>
<th data-quarto-table-cell-role="th">DiastolicBP</th>
<th data-quarto-table-cell-role="th">BS</th>
<th data-quarto-table-cell-role="th">BodyTemp</th>
<th data-quarto-table-cell-role="th">HeartRate</th>
<th data-quarto-table-cell-role="th">RiskLevel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>25</td>
<td>130</td>
<td>80</td>
<td>15.0</td>
<td>98.0</td>
<td>86</td>
<td>high risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>35</td>
<td>140</td>
<td>90</td>
<td>13.0</td>
<td>98.0</td>
<td>70</td>
<td>high risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>29</td>
<td>90</td>
<td>70</td>
<td>8.0</td>
<td>100.0</td>
<td>80</td>
<td>high risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>30</td>
<td>140</td>
<td>85</td>
<td>7.0</td>
<td>98.0</td>
<td>70</td>
<td>high risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>35</td>
<td>120</td>
<td>60</td>
<td>6.1</td>
<td>98.0</td>
<td>76</td>
<td>low risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1009</th>
<td>22</td>
<td>120</td>
<td>60</td>
<td>15.0</td>
<td>98.0</td>
<td>80</td>
<td>high risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1010</th>
<td>55</td>
<td>120</td>
<td>90</td>
<td>18.0</td>
<td>98.0</td>
<td>60</td>
<td>high risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1011</th>
<td>35</td>
<td>85</td>
<td>60</td>
<td>19.0</td>
<td>98.0</td>
<td>86</td>
<td>high risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1012</th>
<td>43</td>
<td>120</td>
<td>90</td>
<td>18.0</td>
<td>98.0</td>
<td>70</td>
<td>high risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1013</th>
<td>32</td>
<td>120</td>
<td>65</td>
<td>6.0</td>
<td>101.0</td>
<td>76</td>
<td>mid risk</td>
</tr>
</tbody>
</table>

<p>1014 rows × 7 columns</p>
</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="5">
<div id="tbl-train-data" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-train-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Training Data Split
</figcaption>
<div aria-describedby="tbl-train-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">SystolicBP</th>
<th data-quarto-table-cell-role="th">DiastolicBP</th>
<th data-quarto-table-cell-role="th">BS</th>
<th data-quarto-table-cell-role="th">BodyTemp</th>
<th data-quarto-table-cell-role="th">HeartRate</th>
<th data-quarto-table-cell-role="th">RiskLevel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1003</th>
<td>50</td>
<td>130</td>
<td>100</td>
<td>16.0</td>
<td>98.0</td>
<td>76</td>
<td>high risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">243</th>
<td>32</td>
<td>120</td>
<td>65</td>
<td>6.0</td>
<td>101.0</td>
<td>76</td>
<td>mid risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">848</th>
<td>15</td>
<td>70</td>
<td>50</td>
<td>6.0</td>
<td>98.0</td>
<td>70</td>
<td>mid risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">202</th>
<td>23</td>
<td>90</td>
<td>60</td>
<td>7.5</td>
<td>98.0</td>
<td>76</td>
<td>low risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">300</th>
<td>15</td>
<td>75</td>
<td>49</td>
<td>7.7</td>
<td>98.0</td>
<td>77</td>
<td>low risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">988</th>
<td>25</td>
<td>120</td>
<td>90</td>
<td>12.0</td>
<td>101.0</td>
<td>80</td>
<td>high risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">322</th>
<td>65</td>
<td>90</td>
<td>60</td>
<td>6.9</td>
<td>98.0</td>
<td>70</td>
<td>low risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">382</th>
<td>17</td>
<td>90</td>
<td>65</td>
<td>7.8</td>
<td>103.0</td>
<td>67</td>
<td>high risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">365</th>
<td>22</td>
<td>120</td>
<td>90</td>
<td>7.8</td>
<td>98.0</td>
<td>82</td>
<td>mid risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">510</th>
<td>17</td>
<td>90</td>
<td>63</td>
<td>7.5</td>
<td>101.0</td>
<td>70</td>
<td>low risk</td>
</tr>
</tbody>
</table>

<p>709 rows × 7 columns</p>
</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="6">
<div id="tbl-test-data" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-test-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Testing Data Split
</figcaption>
<div aria-describedby="tbl-test-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">SystolicBP</th>
<th data-quarto-table-cell-role="th">DiastolicBP</th>
<th data-quarto-table-cell-role="th">BS</th>
<th data-quarto-table-cell-role="th">BodyTemp</th>
<th data-quarto-table-cell-role="th">HeartRate</th>
<th data-quarto-table-cell-role="th">RiskLevel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">50</th>
<td>25</td>
<td>120</td>
<td>80</td>
<td>7.0</td>
<td>98.0</td>
<td>66</td>
<td>low risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">784</th>
<td>35</td>
<td>100</td>
<td>70</td>
<td>6.8</td>
<td>98.0</td>
<td>60</td>
<td>mid risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">204</th>
<td>15</td>
<td>76</td>
<td>49</td>
<td>7.5</td>
<td>98.0</td>
<td>77</td>
<td>low risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">85</th>
<td>18</td>
<td>90</td>
<td>60</td>
<td>6.9</td>
<td>98.0</td>
<td>70</td>
<td>mid risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">802</th>
<td>42</td>
<td>130</td>
<td>80</td>
<td>18.0</td>
<td>98.0</td>
<td>70</td>
<td>mid risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">619</th>
<td>29</td>
<td>130</td>
<td>70</td>
<td>7.5</td>
<td>98.0</td>
<td>78</td>
<td>mid risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">607</th>
<td>45</td>
<td>120</td>
<td>95</td>
<td>7.5</td>
<td>98.0</td>
<td>66</td>
<td>low risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">700</th>
<td>15</td>
<td>120</td>
<td>80</td>
<td>6.6</td>
<td>99.0</td>
<td>70</td>
<td>low risk</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1005</th>
<td>17</td>
<td>90</td>
<td>65</td>
<td>7.7</td>
<td>103.0</td>
<td>67</td>
<td>high risk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">178</th>
<td>40</td>
<td>120</td>
<td>95</td>
<td>11.0</td>
<td>98.0</td>
<td>80</td>
<td>high risk</td>
</tr>
</tbody>
</table>

<p>305 rows × 7 columns</p>
</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="7">
<div id="tbl-risk-counts" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-risk-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Risk Level Counts in Training Data
</figcaption>
<div aria-describedby="tbl-risk-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>RiskLevel
low risk     286
mid risk     238
high risk    185
Name: count, dtype: int64</code></pre>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="eda" class="level2">
<h2 class="anchored" data-anchor-id="eda">EDA</h2>
<p>Preliminary exploratory data analysis (EDA) was performed to briefly examine each explanatory variable. Previous research have described hypertension as a complication risk; therefore, we dropped diastolic BP for the more commonly significant systolic. Distributions of each explanatory variable were plotted using histograms and coloured according to risk levels <a href="#fig-eda-distributions" class="quarto-xref">Figure&nbsp;1</a> (blue: high risk, green: medium risk, orange: low risk). The plotted distibutions were visually distinct across risk levels. Thus, we continued to fit our model with the remaining features.</p>
<div id="fig-eda-distributions" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eda-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eda-distributions" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eda-distributions-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-eda-distributions-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-eda-distributions-output-1.png" data-ref-parent="fig-eda-distributions" width="597" height="429" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-eda-distributions-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Age Distribution
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eda-distributions" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eda-distributions-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-eda-distributions-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-eda-distributions-output-2.png" data-ref-parent="fig-eda-distributions" width="589" height="429" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-eda-distributions-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Systolic BP Distribution
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eda-distributions" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eda-distributions-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-eda-distributions-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-eda-distributions-output-3.png" data-ref-parent="fig-eda-distributions" width="589" height="429" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-eda-distributions-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Blood Sugar Distribution
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eda-distributions" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eda-distributions-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-eda-distributions-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-eda-distributions-output-4.png" data-ref-parent="fig-eda-distributions" width="576" height="429" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-eda-distributions-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Body Temp Distribution
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-eda-distributions" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-eda-distributions-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-eda-distributions-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-eda-distributions-output-5.png" data-ref-parent="fig-eda-distributions" width="589" height="431" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-eda-distributions-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) Heart Rate Distribution
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eda-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Comparison of the distributions of features contributing to the risk intensity level.
</figcaption>
</figure>
</div>
</section>
<section id="data-validation" class="level2">
<h2 class="anchored" data-anchor-id="data-validation">Data Validation</h2>
<section id="validation-ranges" class="level3">
<h3 class="anchored" data-anchor-id="validation-ranges">Validation Ranges</h3>
<p>For <code>Age</code>, we chose a validation range of 10-65 years. The lower limit of 10 accounts for rare cases of very early pregnancy, though pregnancies below the age of 15 are generally medically concerning. The upper limit of 65 represents the maximum biologically feasible range for pregnancy, though pregnancies beyond menopause are extremely rare and would usually require medical intervention. In very rare cases, values outside this range may occur but we can consider them extreme outliers, not suitable for our prediction task.</p>
<p>For <code>SystolicBP</code>, we chose a validation range of 60-200 mmHg. Systolic blood pressure below 60 mmHg indicates severe hypotension, whereas systolic blood pressure above 200 mmHg indicates severe hypertension, both of which are life-threatening emergencies requiring immediate medical intervention. Since our model aims to classify routine maternal health risk levels, values outside the validation range are outside the scope of our classification model and would be considered outliers.</p>
<p>For <code>DiastolicBP</code>, we chose a validation range of 40-140 mmHg. Diastolic blood pressure below 40 mmHg indicates severe hypotension, whereas diastolic blood pressure above 140 mmHg indicates severe hypertension, both of which are life-threatening emergencies requiring immediate medical intervention. Since our model aims to classify routine maternal health risk levels, values outside the validation range are outside the scope of our classification model and would be considered outliers.</p>
<p>For <code>BS</code>, we chose a validation range of 1-25 mmol/L. Blood sugar below 1 mmol/L indicates severe hypoglycemia, whereas blood sugar above 25 mmol/L indicates severe hyperglycemia. Both of these are life-threatening emergencies requiring immediate hospitalization and can therefore be considered unsuitable for our predictive model.</p>
<p>For <code>BodyTemp</code>, we chose a validation range of 95.0-105.0°F. Body temperature below 95.0°F indicates severe hypothermia, whereas body temperature above 105.0°F indicates severe hyperthermia. Both of these are life-threatening emergencies requiring immediate hospitalization and can therefore be considered as unsuitable for our predictive model.</p>
<p>For <code>HeartRate</code>, we chose a validation range of 50-150 bpm. A resting heart rate below 50 bpm or above 150 bpm suggests potential cardiovascular problems requiring immediate medical intervention. Neither of the extreme values is compatible with normal maternal health assessment, and such values can be considered outliers.</p>
<p>The target variable <code>RiskLevel</code> is a categorical variable representing the maternal health risk classification based on clinical assessment. Each observation must contain exactly one of these three risk levels: <code>low risk</code>, <code>mid risk</code> and <code>high risk</code>.</p>
<p>To ensure that the target variable is not severely imbalanced, we applied a minimum class frequency check (at least 5% per class). This avoids situations where certain risk levels are too rare for the model to learn meaningful patterns, which could lead to biased predictions.</p>
<div id="d2a411c2" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Data shape before validation:
(1014, 7)
Data shape after validation:
(1010, 7)</code></pre>
</div>
</div>
<section id="validation-range-results" class="level4">
<h4 class="anchored" data-anchor-id="validation-range-results">Validation Range Results</h4>
<p>We dropped 4 observations during our preliminary data validation, as these rows contain invalid data entires that would introduce noise into our model. More details about which observations have been dropped can be found under <code>validation_errors.log</code> in the <code>notebooks</code> folder.</p>
<p>The validation log shows that the dropped observations include: - 2 rows with <code>Age</code> outside the expected range (10-65 years): ages 66 and 70 - 2 rows with <code>HeartRate</code> of 7 bpm, which seems an impossibility for living people</p>
</section>
<section id="duplicate-observations" class="level4">
<h4 class="anchored" data-anchor-id="duplicate-observations">Duplicate Observations</h4>
<p>We have retained the 562 duplicate rows found in our data validation checks. Since the <a href="https://archive.ics.uci.edu/dataset/863/maternal+health+risk">original data set</a> lacks unique patient identifiers (no patient ID or timestamp), we cannot definitely determine whether these duplicates represent the same patient measured multiple times or different patients with identical measurements. Given this uncertainty and the substantial dataset reduction that would result from removing the duplicates, we opted to keep all duplicate rows and only remove observations that clearly fail other data validation checks.</p>
<p>The dataset passed all other validation checks, namely: - Correct data file format - Correct column names - No empty observations - Missingness not beyond expected threshold: all columns have &lt;5% missing values (threshold = 0.05) - Correct data types in each column - Correct category levels: all categorical values match expected levels - No outliers: all numeric values fall within reasonable ranges (with the exception of the 4 dropped rows) - Target/response variable follows expected distribution</p>
<p>Our final validated dataset <code>validated_data</code> contains 1,010 observations.</p>
<div class="cell" data-execution_count="13">
<div id="tbl-data-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="13">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Descriptive Statistics of Health Data
</figcaption>
<div aria-describedby="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">SystolicBP</th>
<th data-quarto-table-cell-role="th">DiastolicBP</th>
<th data-quarto-table-cell-role="th">BS</th>
<th data-quarto-table-cell-role="th">BodyTemp</th>
<th data-quarto-table-cell-role="th">HeartRate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>1014.000000</td>
<td>1014.000000</td>
<td>1014.000000</td>
<td>1014.000000</td>
<td>1014.000000</td>
<td>1014.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>29.871795</td>
<td>113.198225</td>
<td>76.460552</td>
<td>8.725986</td>
<td>98.665089</td>
<td>74.301775</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>13.474386</td>
<td>18.403913</td>
<td>13.885796</td>
<td>3.293532</td>
<td>1.371384</td>
<td>8.088702</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>10.000000</td>
<td>70.000000</td>
<td>49.000000</td>
<td>6.000000</td>
<td>98.000000</td>
<td>7.000000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>19.000000</td>
<td>100.000000</td>
<td>65.000000</td>
<td>6.900000</td>
<td>98.000000</td>
<td>70.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>26.000000</td>
<td>120.000000</td>
<td>80.000000</td>
<td>7.500000</td>
<td>98.000000</td>
<td>76.000000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>39.000000</td>
<td>120.000000</td>
<td>90.000000</td>
<td>8.000000</td>
<td>98.000000</td>
<td>80.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>70.000000</td>
<td>160.000000</td>
<td>100.000000</td>
<td>19.000000</td>
<td>103.000000</td>
<td>90.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div id="1b30c1f7" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          1014 non-null   int64  
 1   SystolicBP   1014 non-null   int64  
 2   DiastolicBP  1014 non-null   int64  
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64  
 6   RiskLevel    1014 non-null   object 
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB</code></pre>
</div>
</div>
</section>
</section>
<section id="correlations" class="level3">
<h3 class="anchored" data-anchor-id="correlations">Correlations</h3>
<section id="target-feature-correlation" class="level4">
<h4 class="anchored" data-anchor-id="target-feature-correlation">Target-Feature Correlation</h4>
</section>
<section id="feature-feature-correlation" class="level4">
<h4 class="anchored" data-anchor-id="feature-feature-correlation">Feature-Feature Correlation</h4>
</section>
<section id="correlation-validation-results" class="level4">
<h4 class="anchored" data-anchor-id="correlation-validation-results">Correlation Validation Results</h4>
<p>To ensure that our predictive modeling process does not rely on spurious or overly strong relationships, we performed two correlation-based data validation checks on the training split only (to avoid test-set leakage):</p>
<ol type="1">
<li>Target–Feature Correlation Check</li>
</ol>
<p>We applied the FeatureLabelCorrelation check from Deepchecks (used Pandera for a similar test if Deepchecks can’t be used). This check evaluates whether any feature has an strong relationship with the target variable (RiskLevel), which could be a sign of target leakage. Threshold used: correlation &lt; 0.9</p>
<p>Result: All features met the threshold. No anomalous or suspiciously high correlations were detected between features and the target.</p>
<ol start="2" type="1">
<li>Feature–Feature Correlation Check</li>
</ol>
<p>We also used Deepchecks’ FeatureFeatureCorrelation` to check for unusually high correlations between pairs of features, which may indicate redundancy or multicolinearity in modeling.</p>
<p>Result: Feature–feature correlations met the threshold. No pairs of features exhibited extremely high correlation that would require removal or special handling.</p>
</section>
</section>
<section id="overall-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="overall-conclusion">Overall Conclusion</h3>
<p>The validated dataset was confirmed to be within acceptable ranges and both correlation checks passed. There were no failing rows, and no features required modification or exclusion based on these validation steps. This suggests that the dataset has no correlation-based anomalies, and is appropriate for next step of model training.</p>
</section>
</section>
<section id="model-construction" class="level2">
<h2 class="anchored" data-anchor-id="model-construction">Model construction</h2>
<p>We selected a Support Vector Classifier (SVC) model for this classification task. To identify the model configuration that best predicted maternal health risk levels, we performed hyperparameter tuning using randomized search with 10-fold cross-validation and recall score (weighted) as our evaluation metric to select the optimal values for C (regularization parameter), gamma (kernel coefficient). We found that the optimal hyperparameters were 760 for C and 5.8 for gamma.</p>
<div class="cell" data-execution_count="24">
<div id="tbl-dummy-score" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="24">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dummy-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Dummy Classifier Cross-Validation Scores
</figcaption>
<div aria-describedby="tbl-dummy-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="24">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fit_time</th>
<th data-quarto-table-cell-role="th">score_time</th>
<th data-quarto-table-cell-role="th">test_score</th>
<th data-quarto-table-cell-role="th">train_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0.000483</td>
<td>0.000745</td>
<td>0.401408</td>
<td>0.403880</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0.000366</td>
<td>0.000282</td>
<td>0.401408</td>
<td>0.403880</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0.000342</td>
<td>0.000286</td>
<td>0.401408</td>
<td>0.403880</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>0.000344</td>
<td>0.000263</td>
<td>0.408451</td>
<td>0.402116</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>0.000350</td>
<td>0.000255</td>
<td>0.404255</td>
<td>0.403169</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="27">
<div id="tbl-svc-score" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="27">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-svc-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: SVC Cross-Validation Scores (Default)
</figcaption>
<div aria-describedby="tbl-svc-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fit_time</th>
<th data-quarto-table-cell-role="th">score_time</th>
<th data-quarto-table-cell-role="th">test_score</th>
<th data-quarto-table-cell-role="th">train_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0.011944</td>
<td>0.004028</td>
<td>0.725352</td>
<td>0.707231</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0.007503</td>
<td>0.002931</td>
<td>0.676056</td>
<td>0.719577</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0.007589</td>
<td>0.002840</td>
<td>0.718310</td>
<td>0.719577</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>0.007249</td>
<td>0.002728</td>
<td>0.711268</td>
<td>0.708995</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>0.007000</td>
<td>0.002681</td>
<td>0.659574</td>
<td>0.727113</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<section id="hyperparameter-tuning" class="level3">
<h3 class="anchored" data-anchor-id="hyperparameter-tuning">Hyperparameter tuning</h3>
<p>In order to classify clinical risk levels, recall score was selected as the preferred evaluation metric. This is because recall score measures the percentage correctly identified of actual high-risk pregnancies. This is critical for maternal health prediction where false negatives could result in missing high-risk, vulnerable individuals. Although prioritizing recall could increase the rate of false positive errors, it is the safer choice in this context.</p>
<div class="cell" data-execution_count="29">
<div id="tbl-svc-recall" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="29">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-svc-recall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: SVC Cross-Validation Scores (Recall Weighted)
</figcaption>
<div aria-describedby="tbl-svc-recall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fit_time</th>
<th data-quarto-table-cell-role="th">score_time</th>
<th data-quarto-table-cell-role="th">test_score</th>
<th data-quarto-table-cell-role="th">train_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0.007424</td>
<td>0.003930</td>
<td>0.725352</td>
<td>0.707231</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0.007210</td>
<td>0.003595</td>
<td>0.676056</td>
<td>0.719577</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0.007386</td>
<td>0.003551</td>
<td>0.718310</td>
<td>0.719577</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>0.007106</td>
<td>0.003439</td>
<td>0.711268</td>
<td>0.708995</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>0.006930</td>
<td>0.003469</td>
<td>0.659574</td>
<td>0.727113</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div id="99dfab73" class="cell" data-execution_count="32">
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>0.7615895372233401</code></pre>
</div>
</div>
<div id="cell-fig-hyperparam-heatmap" class="cell" data-execution_count="34">
<div class="cell-output cell-output-display">
<div id="fig-hyperparam-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hyperparam-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-hyperparam-heatmap-output-1.png" width="1071" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hyperparam-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Results from hyperparameter optimization and 10-fold cross validation to choose gamma and C. Recall score was used as the classification metric as gamma and C was varied.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="39">
<div id="tbl-crosstab" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="39">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-crosstab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Crosstab of Actual vs Predicted Risk Levels
</figcaption>
<div aria-describedby="tbl-crosstab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="39">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">predicted</th>
<th data-quarto-table-cell-role="th">high risk</th>
<th data-quarto-table-cell-role="th">low risk</th>
<th data-quarto-table-cell-role="th">mid risk</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">actual</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">high risk</th>
<td>74</td>
<td>2</td>
<td>11</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">low risk</th>
<td>4</td>
<td>95</td>
<td>21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">mid risk</th>
<td>9</td>
<td>19</td>
<td>70</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div id="cell-fig-confusion-matrix" class="cell" data-execution_count="40">
<div class="cell-output cell-output-display">
<div id="fig-confusion-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-confusion-matrix-output-1.png" width="545" height="429" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Confusion matrix of model performance on test data.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-roc-curve" class="cell" data-execution_count="41">
<div class="cell-output cell-output-stdout">
<pre><code>high risk: AUC = 0.953
low risk: AUC = 0.884
mid risk: AUC = 0.858</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-roc-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-roc-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="health_analysis_files/figure-html/fig-roc-curve-output-2.png" width="521" height="528" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roc-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: ROC curve of model performance on test data.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="summary-of-model-results" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-model-results">Summary of Model Results</h3>
<p>The final SVC classifier performed fairly well on an unseen test data set, with a weighted recall score of 0.77 and an overall accuracy of 0.77. Out of the 305 test data cases, it correctly predicted 235 cases. The model showed particularly strong performance in identifying high-risk pregnancies, achieving an AUC of 0.953 for the high-risk class, compared to 0.884 for low-risk class and 0.858 for medium-risk class. It correctly identifies 74 out of 87 actual high-risk pregnancies resulting in a 85% recall for high risk. There were 13 notable errors in which true high-risk cases were misclassified as 11 medium-risk and 2 low-risk.</p>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The latest interation of the SVC model delivered promising results and demonstrated considerable accuracy when classifying high-risk individuals. Correct identification of high-risk individuals is pivotal in the prevention and early intervention of pregnancy complications, such as hemorrhaging and eclampsia. The model’s ability to correctly classify high-risk inviduals is encouraging, and future interations could help alert doctors or emergency responders to improve accessibility for underserved communities.</p>
<p>Further refinement is required, however, as the model made 13 notable classification errors during testing. 13 truely high-risk cases were misclassified as 11 medium-risk and 2 low-risk. In reality, these false negatives are gaps where high-risk individuals could be overlooked and not prioritized appropriately. Future versions should seek to improve the model’s sensitivity to high-risk cases and better differentiate between medium and low-risk categories before it is ready to be implemented in clinical settings.</p>
<p>A limitation of this model is that other devices and their sensors may have different measurement accuracies and calibration standards. The model was trained on data collected from specific IoT devices in rural Bangladesh; therefore, its performance may vary when applied to data from different devices or populations. Additionally, other countries may have health information documentation standards that differ from Bangladesh. Future work should consider validating the model across diverse datasets and device types to ensure its robustness and generalizability.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Global maternal mortality rates are on the decline; however, there remains unmet needs within many developing and underserved communities. Greater emphasis on primary prevention and early identification would enable better management of pregnancy complications and improve health outcomes overall. This report demonstrates the potential of machine learning models and at-home monitoring devices. With further improvement, these tools could create opportunities for more focused, effective, and resourceful delivery of care.</p>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ahmed2020data" class="csl-entry" role="listitem">
Ahmed, M., M. A. Kashem, M. Rahman, and S. Khatun. 2020. <span>“Review and Analysis of Risk Factor of Maternal Health in Remote Area Using the Internet of Things (IoT).”</span> Springer. <a href="https://doi.org/10.1007/978-981-15-2317-5_30">https://doi.org/10.1007/978-981-15-2317-5_30</a>.
</div>
<div id="ref-niels_bantilan_2023_pandera" class="csl-entry" role="listitem">
Bantilan, Niels. 2023. <span>“Pandera: Statistical Data Validation of Pandas Dataframes.”</span> Zenodo. <a href="https://github.com/unionai-oss/pandera">https://github.com/unionai-oss/pandera</a>.
</div>
<div id="ref-deepchecks" class="csl-entry" role="listitem">
Deepchecks. 2022. <span>“Deepchecks: A Library for Testing and Validating Machine Learning Models and Data.”</span> <a href="https://github.com/deepchecks/deepchecks">https://github.com/deepchecks/deepchecks</a>.
</div>
<div id="ref-harris2020array" class="csl-entry" role="listitem">
Harris, Charles R., K. Jarrod Millman, Stéfan J. van der Walt, Ralf Gommers, Pauli Virtanen, David Cournapeau, Eric Wieser, et al. 2020. <span>“Array Programming with <span>NumPy</span>.”</span> <em>Nature</em> 585 (7825): 357–62. <a href="https://doi.org/10.1038/s41586-020-2649-2">https://doi.org/10.1038/s41586-020-2649-2</a>.
</div>
<div id="ref-hassfurter2025trends" class="csl-entry" role="listitem">
Hassfurter, K. 2025. <span>“Trends in Maternal Mortality 2000 to 2023 - UNICEF DATA.”</span> UNICEF DATA. <a href="https://data.unicef.org/resources/trends-in-maternal-mortality-2000-to-2023/">https://data.unicef.org/resources/trends-in-maternal-mortality-2000-to-2023/</a>.
</div>
<div id="ref-hossain2023maternal" class="csl-entry" role="listitem">
Hossain, A. B. M. Sharif, A. Siddique, S. Jabeen, S. Khan, M. Moinuddin Haider, S. Ameen, Tazeen Tahsina, et al. 2023. <span>“Maternal Mortality in Bangladesh: Who, When, Why, and Where? A National Survey-Based Analysis.”</span> <em>Journal of Global Health</em> 13. <a href="https://doi.org/10.7189/jogh.13.07002">https://doi.org/10.7189/jogh.13.07002</a>.
</div>
<div id="ref-hunter2007matplotlib" class="csl-entry" role="listitem">
Hunter, John D. 2007. <span>“Matplotlib: A 2D Graphics Environment.”</span> <em>Computing in Science &amp; Engineering</em> 9 (3): 90–95.
</div>
<div id="ref-mckinney2010data" class="csl-entry" role="listitem">
McKinney, Wes et al. 2010. <span>“Data Structures for Statistical Computing in Python.”</span> In <em>Proceedings of the 9th Python in Science Conference</em>, 445:51–56. Austin, TX.
</div>
<div id="ref-pedregosa2011scikit" class="csl-entry" role="listitem">
Pedregosa, Fabian, Gaël Varoquaux, Alexandre Gramfort, Vincent Michel, Bertrand Thirion, Olivier Grisel, Mathieu Blondel, et al. 2011. <span>“Scikit-Learn: Machine Learning in Python.”</span> <em>Journal of Machine Learning Research</em> 12 (Oct): 2825–30.
</div>
<div id="ref-reitz2023requests" class="csl-entry" role="listitem">
Reitz, Kenneth et al. 2023. <span>“Requests: HTTP for Humans.”</span> <a href="https://requests.readthedocs.io">https://requests.readthedocs.io</a>.
</div>
<div id="ref-souza2023global" class="csl-entry" role="listitem">
Souza, J. P., L. Day, A. C. Rezende-Gomes, J. Zhang, R. Mori, A. Baguiya, K. Jayaratne, et al. 2023. <span>“A Global Analysis of the Determinants of Maternal Health and Transitions in Maternal Mortality.”</span> <em>The Lancet Global Health</em> 12 (2). <a href="https://doi.org/10.1016/s2214-109x(23)00468-0">https://doi.org/10.1016/s2214-109x(23)00468-0</a>.
</div>
<div id="ref-vanderplas2018altair" class="csl-entry" role="listitem">
VanderPlas, Jacob, Brian Granger, Jeffrey Heer, Dominik Moritz, Kanit Wongsuphasawat, Arvind Satyanarayan, Eitan Lees, Ilia Timofeev, Ben Welsh, and Scott Sievert. 2018. <span>“Altair: Interactive Statistical Visualizations for Python.”</span> <em>Journal of Open Source Software</em> 3 (32): 1057.
</div>
<div id="ref-virtanen2020scipy" class="csl-entry" role="listitem">
Virtanen, Pauli, Ralf Gommers, Travis E Oliphant, Matt Haberland, Tyler Reddy, David Cournapeau, Evgeni Burovski, et al. 2020. <span>“SciPy 1.0: Fundamental Algorithms for Scientific Computing in Python.”</span> <em>Nature Methods</em> 17 (3): 261–72.
</div>
<div id="ref-waskom2021seaborn" class="csl-entry" role="listitem">
Waskom, Michael L. 2021. <span>“Seaborn: Statistical Data Visualization.”</span> <em>Journal of Open Source Software</em> 6 (60): 3021. <a href="https://doi.org/10.21105/joss.03021">https://doi.org/10.21105/joss.03021</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>